web:
  image: 'gitlab/gitlab-ce:latest'
  restart: always
  hostname: 'gitlab.$TLD_URL'
  environment:
    GITLAB_OMNIBUS_CONFIG: |
      external_url 'https://gitlab.$TLD_URL:2224'
      gitlab_rails['gitlab_shell_ssh_port'] = 2224
  ports:
    - '8929:8929'
    - '2224:22'
  volumes:
    - '$HOME/config:/etc/gitlab'
    - '$HOME/logs:/var/log/gitlab'
    - '$HOME/data:/var/opt/gitlab'
